config/routes.rb
Worklista::Application.routes.draw do

  # OAuth callback point
  match "auth/:provider/callback" => "authentications#callback_handler"

  # Different ways to show user's item
  match "users/:username/popular" => "users#popular", :as => "user_popular", :via => "get"
  match "users/:username/pickup" => "users#pickup", :as => "user_pickup", :via => "get"
  match "users/:username" => "users#show", :as => "user_recent", :via => "get"
  match "users/:username/tag/:tag" => "users#tag", :as => "user_tag", :via => "get"

  # Export user's data
  match "/users/:username/export" => "users#export_xml"

  # Routes for items
  resources :users do
    resources :items
  end
  match "items/" => "items#index", :as => "item_index", :via => "get"
  match "tag/:tag" => "items#tag", :as => "tag", :via => "get"
  match "/users/:user_id/items/:id/toggle" => "items#toggle_pick", :as => "toggle_pick", :via => "put"

  # Routes for users and devise authentication
  match "/users" => "users#index"
  devise_for :users, :path => 'account', :controllers => {:registrations => "registrations"} do
    get "login",  :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "account",   :to => "devise/registrations#edit"
  end
  
  # Static pages and the root
  root :to => "pages#home"
  match "/about" => "pages#about"
  match "/faq" => "pages#faq"

  # Error handling
  match '*a', :to => 'errors#routing'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  attr_accessible :email, :username, :name, :title, :twitter_id, \
  :description, :website, :password, :password_confirmation, :remember_me,\
  :photo, :invite_code, :remote_photo_url, :provider, :uid
  attr_accessor :invite_code

  paginates_per 8

  # Validations

  validates_length_of :name, :within => 3..30, :allow_nil => true
  validates_uniqueness_of :username
  validates_length_of :username,    :within  => 3..24
  validates_format_of :username,    :with    => /\A[_a-zA-Z0-9]+\Z/
  validates_format_of :twitter_id,  :with    => /\A[_a-zA-Z0-9]+\Z/, :allow_nil => true, :allow_blank => true
  validates :website, :format => {:with => URI::regexp(%w(http https))}, :allow_nil => true, :allow_blank => true
  validates_length_of :description, :maximum => 160

  # Plugins

  has_attached_file :photo,
                    :styles => { :medium => "240x240", :thumb => "80x80",
                                 :original => "300x300"}, 
                    :default_url => "/images/missing-:style.png"
  validates_attachment_size :photo, :less_than => 1.megabytes

  # Override login key to use username OR email (for devise)

  def self.find_for_database_authentication(conditions)
    value = conditions[authentication_keys.first]
    u = where(["username = :value OR email = :value", { :value => value }]).first
    u.provider ? nil:u 
  end

  # to allow users to edit their accout without providing a password

  def update_with_password(params={}) 
    if params[:password].blank? 
      params.delete(:password) 
      params.delete(:password_confirmation) if params[:password_confirmation].blank? 
    end 
    update_attributes(params) 
  end 

  def self.auth_new(auth)
    info = auth['user_info']
    nickname = info['nickname'].gsub(/\./,'') || info['name'].gsub(/\. /,'')
    username = User.available_name(nickname)
    remote_photo_url = info['image']
    case auth['provider']
    when "twitter"
      description      = info['description']
      twitter_id       = info['nickname']
      website          = info['urls']['Website']
    when "facebook"
      description      = ''
      twitter_id       = ''
      website          = info['urls']['Website'] || info['urls']['Facebook']
    end
    user = User.new(:name => info['name'],
                    :username => username,
                    # dirty password and email strings to comply with devise
                    :password => "hogehoge",
                    :email => username + Time.now.strftime("%Y%m%d%H%M%S") + "@worklista.com",
                    :description => description,
                    :remote_photo_url => remote_photo_url,
                    :twitter_id => twitter_id,
                    :website => website,
                    :provider => auth['provider'],
                    :uid => auth['uid'])
    user.normalize_photo_url
    user
  end

  def normalize_photo_url
    case self.provider
    when "twitter"
      self.remote_photo_url = self.remote_photo_url.gsub(/_normal/,'')
    when "facebook"
      url = URI.parse(self.remote_photo_url.gsub(/\?type.+/,''))
      req = Net::HTTP::Get.new(url.path)
      res = Net::HTTP.start(url.host, url.port){|http| http.request(req)}
      self.remote_photo_url = res.response['location'].gsub(/_q/,'')
    end
  end

  def self.available_name(nickname)
    suffix = false
    unless User.where(:username => nickname).first
      nickname
    else
      # need to give users better UI to change the temporal
      # username when collision occured.
      suffix = 1
      new_name = nickname + suffix.to_s
      while User.where(:username => new_name).first
        suffix = suffix + 1
        new_name = nickname + suffix.to_s
      end
      new_name
    end
  end
end

app/controllers/users_controller.rb
require 'open-uri'

class UsersController < ApplicationController
  before_filter :find_user, :except => [:index, :create]

  def index
    @users = User.order("last_item_updated_at DESC").page params[:page]
  end

  def tag
    @tag = params[:tag]
    @items = @items.tagged(@tag).order("published_at DESC").page params[:page]
    if (@size = @items.size).zero?
      flash[:error] = "Tag you specified: #{params[:tag]} does not exist."
      redirect_to user_recent_path
    else
      @select = :recent
      render "me"
    end
  end

  def show
    @items = @items.order("published_at DESC").page params[:page]
    @select = :recent
    respond_to do |format|
      format.html { render "me"}
      format.atom
    end
  end

  def popular
    @items = @items.order("hatena DESC").page params[:page]
    @select = :popular
    render "me"
  end

  def pickup
    @items = @items.where({:pick => true}).order("published_at DESC").page params[:page]
    @size = @items.size
    @select = :pickup
    render "me"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      logger.info "Stats: registered a new user  : #{@user.username} via #{@user.provider} #{Time.now}"
      flash[:notice] = "Welcome #{@user.username} ! Any changes here? Click on Me button to start adding your items!"
      sign_in @user
      redirect_to '/account'
    else
      flash[:error] = "Something went wrong with Twitter login..."
      redirect_to '/'
    end
  end

  def export_xml
    @list = @items.map do |i|
      {title: i.title,
        url: i.url,
        tags: i.tag_names,
        summary: i.summary,
        date: i.published_at}
    end
    render :xml => @list.to_xml
  end

private

  def find_user
    @user  = User.where("username = ?", params[:username]).first
    if @user.nil?
      flash[:error] = "The username you specified, #{params[:username]} does not exist."
      redirect_to users_path
    else
      @items = Item.where({:user_id => @user.id})
      @size  = @items.size
    end
  end

end

app/views/users/_edit.html.haml
= form_for(item, :url => "/users/#{user.id}/items/#{item.id}") do |f|
  .inline-edit
    %p
      Title
      = f.text_field :title, :size => 80
    %p{:style => 'font-size: 0.8em; color: grey'}
      = truncstr(item.url, 40)
      %a{:href => item.url, :target => "_blank" } (open in other window)
    %p
      Tags
      = f.text_field :tag_names
    %p
      Date
      = f.date_select :published_at
    %p
      Description
      %br
      = f.text_area :summary, :cols => 60, :rows => 8
      %span{:style => 'font-size: 0.8em; color: grey'} 100
    %p= f.submit "Update"
    %p (Hit escape key if there is nothing to change)

app/views/users/_item.html.haml
.item{:id => "item_#{i.id}"}
  .head
    .title
      %a{:href => i.url, :target => "_blank" }
        = truncstr(i.title, 40)
    .social
      = raw(social_buttons({:url => i.url, :title => i.title, :user => @user}))
    .date= i.published_at

  .body
    .tags
      - if !i.tags.empty?
        - i.tags.each do |tag|
          %a{:href => user_tag_path(:tag => tag.name)}
            = tag.name
    - if i.summary
      .summary
        = link_to truncstr(i.summary, 80), user_item_path(@user, i)
    .edit-buttons
      - if user_signed_in? && current_user.id == user.id
        = link_to "del", user_item_path(user, i), :confirm => "Are you sure?", :method => :delete, :remote => :true, :class => 'item_delete'
        .item_edit edit
        = render :partial => "users/edit", :locals => {:item => i, :user => @user}
        - if i.pick?
          = link_to "Unpick", toggle_pick_path(user, i), :method => :put, :class => 'item_unpick'
        - else
          = link_to "pick", toggle_pick_path(user, i), :method => :put, :class => 'item_pick'

app/views/users/confirm.html.haml
- title "Confirmation"
%h2= "Create an account with #{user.provider.capitalize} ?"
.profile
  .head
    .photo= image_tag "cache/" + user.provider + user.uid
    .name= user.name
    .username= user.username
  .body
.confirm
  .yes
    = form_for(user) do |f|
      = f.hidden_field :name
      = f.hidden_field :email
      = f.hidden_field :password
      = f.hidden_field :username
      = f.hidden_field :twitter_id
      = f.hidden_field :website
      = f.hidden_field :description
      = f.hidden_field :provider
      = f.hidden_field :uid
      = f.hidden_field :remote_photo_url
      = f.submit "Yes!", :class => "mybutton"
  .no
    = link_to "No, thanks.", '/', :class => "mybutton"
.another_way
  - another = user.provider == "twitter" ? "Facebook" : "Twitter"
  = "If you already have an account, you can login with"
  = link_to another, "/auth/#{another}"

app/views/users/index.html.haml
- title "Users"
- @users.each do |user|
  .profile
    .head
      .photo
        = link_to photo_tag(user, :size => :normal), "/users/#{user.username}"
      .name
        = link_to user.name, "/users/#{user.username}" if user.name
      .username
        = link_to user.username, "/users/#{user.username}"
      .twitter
        - unless user.twitter_id.blank?
          = link_to(image_tag("twitter-icon.png"), "http://twitter.com/#{user.twitter_id}")
        = link_to(image_tag("rss-icon.png"), "http://worklista.com/users/#{user.username}.atom")

      .website
        - if user.website
          = link_to user.website, user.website
    .body
      .description
        = user.description
= paginate @users

app/views/users/me.html.haml
- title @user.username
- feed_tag if @select == :recent
.profile
  .head
    .photo
      %a{:href => "/users/#{@user.username}"}
        = photo_tag(@user, options = {:size => :normal})
    .name= @user.name
    .username
      = link_to @user.username, "/users/#{@user.username}"
    .twitter
      - unless @user.twitter_id.blank?
        = link_to(image_tag("twitter-icon.png"), "http://twitter.com/#{@user.twitter_id}")
      - if @select == :recent
        = link_to(image_tag("rss-icon.png"), "http://worklista.com/users/#{@user.username}.atom")
    .website
      - if @user.website
        = link_to @user.website, @user.website
  .body
    .description=h @user.description

%hr

- if user_signed_in? && current_user.id == @user.id
  #url-form
    = form_for([@user, @user.items.build], :remote => true, :html => {:'data-type' => "html", :id => "url_form" }) do |f|
      URL:
      = f.text_field :url, :size => 55
      = f.submit "Add"
    #error-message

- if @tag
  .tag_link
    %a{:href => tag_path(@tag)} Items tagged as <strong>#{@tag}</strong> by everyone

#item-tab
  %ul
    %li{:class => ('selected' if @select == :recent)}
      = link_to 'Recent', user_path(@user.username)
    %li{:class => ('selected' if @select == :popular)}
      = link_to 'Popular', user_popular_path(@user.username)
    %li{:class => ('selected' if @select == :pickup)}
      = link_to '10 URLs', user_pickup_path(@user.username)

- if @size == 0
  .item
    %p No items

- @items.each do |i|
  =render :partial => "users/item", :locals => {:i => i, :user => @user}

= paginate @items

app/views/users/show.html.haml
- title @user.username
%h1 User Page
#profile
  #head
    #photo
      = image_tag @user.photo.url(:thumb)
    #name= @user.name
    #title= @user.title
    #username= @user.username
    #website= @user.website
  #body
    #description=h @user.description

%p
  = link_to "Edit", edit_user_registration_path
  |
  = link_to "View All", users_path

%hr