config/routes.rb
Worklista::Application.routes.draw do

  # OAuth callback point
  match "auth/:provider/callback" => "authentications#callback_handler"

  # Different ways to show user's item
  match "users/:username/popular" => "users#popular", :as => "user_popular", :via => "get"
  match "users/:username/pickup" => "users#pickup", :as => "user_pickup", :via => "get"
  match "users/:username" => "users#show", :as => "user_recent", :via => "get"
  match "users/:username/tag/:tag" => "users#tag", :as => "user_tag", :via => "get"

  # Export user's data
  match "/users/:username/export" => "users#export_xml"

  # Routes for items
  resources :users do
    resources :items
  end
  match "items/" => "items#index", :as => "item_index", :via => "get"
  match "tag/:tag" => "items#tag", :as => "tag", :via => "get"
  match "/users/:user_id/items/:id/toggle" => "items#toggle_pick", :as => "toggle_pick", :via => "put"

  # Routes for users and devise authentication
  match "/users" => "users#index"
  devise_for :users, :path => 'account', :controllers => {:registrations => "registrations"} do
    get "login",  :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
    get "account",   :to => "devise/registrations#edit"
  end
  
  # Static pages and the root
  root :to => "pages#home"
  match "/about" => "pages#about"
  match "/faq" => "pages#faq"

  # Error handling
  match '*a', :to => 'errors#routing'
end

app/views/pages/about.html.haml
- title "About"
#pages

  %h2 What can I do with this thing? 

  %p Here's the list. 
  %ul
    %li list your work that matters. Only those you want others to take a look at. 
    %li select 10 URLs from the list that would help someone understand your work and areas of interest real quick.
    %li provide your single RSS feed to anyone who cares about what you are up to.
    %li export your list as XML file. 

  %h2 What kind of work do I list up? 

  %p Any kind. For instance, it can be a set of links to your writing(blog entries, articles...), photos, research papers, slides, screencasts and videos. If you get interviewed by someone, you should add that, too. This is a place to show your professional work. 

  %h2 Why not RSS? 

  %p Anyone interested in EVERYTHING you publish online may subscribe to your RSS feeds here and there, or follow/friend you, however, that's simply not the case. It's too cumbersome. 

  %p People are literally fed up with feeds. Some people might subscribe to your blog and spend some months to know what you have to say about things. Others might spend a couple of hours digging your blog entries in the past, searching your name to get a grasp of who you are. Don't let them, anymore.

  %p With Worklista, you can choose which work is going into the list. Someone doing a quick research on you will find this list and get a quick look in a matter of minutes. It's better this way for them and yourself, too. 

  %h2 Googling my name should list up all my work. No? 

  %p Googling your name just yields an okay grasp of you. Maybe, there are people with the same name as yours. Also, you can't control what others have to say about you online. Searching for your name with popular search engines--, what people refer to as ego-search, may list unsolicited URLs like:

  %ul
    %li your outdated information
    %li your outdated work
    %li bad reputation or rumor, which isn't true

  %p They persist in search result. There's little we can do about them. Yes, we must face it. On the other hand, wouldn't it be nice if we could select our GOOD work and try to put this list on top of those search results? 

  %p Managing your work publication with Worklista is like drafting a neat resume. You might have had a personal web site where you listed up your work in order. Good. But, let me ask this question: when was the last time you updated that list? Worklista is a content management system specifically designed for this purpose. 

  %h2 What if somebody claims other people's work as theirs own? 

  %p We don't verify any work: who did what etc,. Be cautious if you are thinking about using this service to do a research on someone. 

  %h2 Who's behind this site?

  %p Ken Nishimura(#{link_to "@knsmr", "http://twitter.com/knsmr"}), a Japanese tech journalist. Worklista started as a personal attempt to solve his own little problem. 

app/views/pages/home.html.haml
- title "Welcome"
#pages{:style => 'background: white;'}
  #home
    .left
      .welcome-message
        3 easy steps:
        %ol
          %li Create
          %li Publish
          %li List
      - unless user_signed_in?
        = link_to 'Sample page', user_recent_path("knsmr"), :class => "mybutton"
        %p
        = link_to 'FAQ', '/about', :class => "mybutton"
    .howitworks
      %img{ :src => "images/howitworks.png", :width => 450}
      %p Do you publish your work such as articles, photos, software programs, anything that has a URL? Want to maintain a decent URL list of them? Worklista can help you a lot!